call scripts\makebabymons.bat
call scripts\makeeggmoves.bat
call scripts\makeevodata.bat
call scripts\makefootprintnarc.bat
call scripts\makeheighttable.bat
call scripts\makelevelupdata.bat
call scripts\makemondata.bat
call scripts\makemoniconnarc.bat
call scripts\makemonspritenarc.bat
call scripts\makemsgnarc.bat
call scripts\makeregionaldexorder.bat
call scripts\makespriteoffsets.bat
call scripts\maketutordata.bat
call scripts\makeoverworldnarc.bat